/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.2--ijk0.7.6--20170203--001"
#endif /* AVUTIL_FFVERSION_H */
